// packages/vue-sdk/src/components/SearchcraftFilterPanel.tsx
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftFilterPanel as Component } from '../stencil-web-components';

export type SearchcraftFilterPanelProps = Partial<Components.SearchcraftFilterPanel>;

export default defineComponent({
  name: 'SearchcraftFilterPanel',
  props: {
    items: {
      type: Array as () => Components.SearchcraftFilterPanel['items'],
      required: true,
    },
  },
  setup(props: SearchcraftFilterPanelProps) {
    return () => <Component {...(props as Components.SearchcraftFilterPanel)} />;
  },
});

// packages/react-sdk/src/components/SearchcraftFilterPanel/index.tsx
import type { FC } from 'react';

import { SearchcraftFilterPanel } from '../../stencil-web-components/components';
import type { FilterItem } from '@searchcraft/javascript-sdk/dist/types/components.js';

export type FilterPanelProps = {
  items: FilterItem[];
};

const FilterPanel: FC<FilterPanelProps> = ({ items = [] }) => (
  <SearchcraftFilterPanel items={items} />
);

export default FilterPanel;
