// packages/react-sdk/src/client/SearchcraftTheme.tsx
import type { FC } from 'react';

import type { Components } from '@searchcraft/javascript-sdk';
import { SearchcraftTheme as Component } from '../stencil-output/components';

/**
 * The Props for the SearchcraftTheme component.
 */
interface SearchcraftThemeProps extends Components.SearchcraftTheme {}

/**
 * A component that applies Searchcraft's built-in CSS theme to your page.
 * It does not render anything visible—its only function is to manage the CSS styles on the page.
 *
 * @example
 * ```tsx
 * import React from 'react';
 * import { SearchcraftTheme } from '@searchcraft/react-sdk';
 *
 * const MyThemeProvider = () => {
 *   return <SearchcraftTheme />;
 * };
 *
 * export default MyThemeProvider;
 * ```
 */
const SearchcraftTheme: FC<SearchcraftThemeProps> = (props) => (
  <Component {...props} />
);

export { SearchcraftTheme };
export type { SearchcraftThemeProps };

// packages/javascript-sdk/src/components/searchcraft-theme/searchcraft-theme.tsx
import { Component, h } from '@stencil/core';
import styles from '../../themes/hologram.css?raw';

/**
 * This web component adds Searchcraft's built-in css theme to your page. It does not render anything visible, its only function is to manage the css styles on the page.'
 *
 * @react-import
 * ```jsx
 * import { SearchcraftTheme } from "@searchcraft/react-sdk";
 * ```
 *
 * @vue-import
 * ```jsx
 * import { SearchcraftTheme } from "@searchcraft/vue-sdk";
 * ```
 *
 * @js-example
 * ```html
 * <searchcraft-theme />
 * ```
 *
 * @react-example
 * ```jsx
 * <SearchcraftTheme />
 * ```
 *
 * @vue-example
 * ```jsx
 * <SearchcraftTheme />
 * ```
 */
@Component({
  tag: 'searchcraft-theme',
  shadow: false,
})
export class SearchcraftTheme {
  render() {
    return <style>{styles}</style>;
  }
}
