// packages/vue-sdk/src/components/SearchcraftFacetList.vue
<script lang="ts">
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftFacetList as Component } from '../stencil-web-components';

export type SearchcraftFacetListProps = Components.SearchcraftFacetList;

export default defineComponent({
  name: 'SearchcraftFacetList',
  props: {
    fieldName: {
      type: String as () => Components.SearchcraftFacetList['fieldName'],
      required: true,
    },
  },
  emits: ['facetSelectionUpdated'],
  components: {
    Component,
  },
});
</script>

<template>
  <Component
    v-bind="$props"
    @facetSelectionUpdated="$emit('facetSelectionUpdated', $event)"
  />
</template>

// packages/react-sdk/src/components/SearchcraftFacetList.tsx
import type { FC } from 'react';

import { SearchcraftFacetList as Component } from '../stencil-web-components/components';
import type { Components } from '@searchcraft/javascript-sdk';

interface SearchcraftFacetListProps extends Components.SearchcraftFacetList {}

const SearchcraftFacetList: FC<SearchcraftFacetListProps> = (props) => (
  <Component {...props} />
);

export { SearchcraftFacetList };
export type { SearchcraftFacetListProps };
