// packages/vue-sdk/src/components/SearchcraftPopoverForm.vue
<script lang="ts">
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftPopoverForm as Component } from '../stencil-web-components';

export type SearchcraftPopoverFormProps = Components.SearchcraftPopoverForm;

export default defineComponent({
  name: 'SearchcraftPopoverForm',
  props: {
    type: {
      type: String as () => SearchcraftPopoverFormProps['type'],
      required: false,
    },
    hotkey: {
      type: String as () => SearchcraftPopoverFormProps['hotkey'],
      required: false,
    },
    hotkeyModifier: {
      type: String as () => SearchcraftPopoverFormProps['hotkeyModifier'],
      required: false,
    },
    config: {
      type: Object as () => SearchcraftPopoverFormProps['config'],
      required: false,
    },
    popoverResultMappings: {
      type: Object as () => SearchcraftPopoverFormProps['popoverResultMappings'],
      required: false,
    },
  },
  components: {
    Component,
  },
});
</script>

<template>
  <Component v-bind="$props" />
</template>

// packages/react-sdk/src/components/SearchcraftPopoverForm.tsx
import type { FC } from 'react';

import type { Components } from '@searchcraft/javascript-sdk';
import { SearchcraftPopoverForm as Component } from '../stencil-web-components/components';

interface SearchcraftPopoverFormProps extends Components.SearchcraftPopoverForm { }

const SearchcraftPopoverForm: FC<SearchcraftPopoverFormProps> = (props) => (
  <Component {...props} />
);

export { SearchcraftPopoverForm };
export type { SearchcraftPopoverFormProps };
