// packages/vue-sdk/src/components/SearchcraftFilterPanel.tsx
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftFilterPanel as Component } from '../stencil-web-components';

export type SearchcraftFilterPanelProps = Partial<Components.SearchcraftFilterPanel>;

export default defineComponent({
  name: 'SearchcraftFilterPanel',
  props: {
    items: {
      type: Array as () => Components.SearchcraftFilterPanel['items'],
      required: true,
    },
  },
  setup(props: SearchcraftFilterPanelProps) {
    return () => <Component {...(props as Components.SearchcraftFilterPanel)} />;
  },
});

// packages/react-sdk/src/components/SearchcraftFilterPanel.tsx
import type { FC } from 'react';

import { SearchcraftFilterPanel as Component } from '../stencil-web-components/components';
import type { Components } from '@searchcraft/javascript-sdk';

interface SearchcraftFilterPanelProps
  extends Components.SearchcraftFilterPanel {}

const SearchcraftFilterPanel: FC<SearchcraftFilterPanelProps> = (props) => (
  <Component {...props} />
);

export { SearchcraftFilterPanel };
export type { SearchcraftFilterPanelProps };
