// packages/vue-sdk/src/components/SearchcraftFacetList.tsx
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftFacetList as Component } from '../stencil-web-components';

// Use the type provided by the SDK for props
export type SearchcraftFacetListProps = Partial<Components.SearchcraftFacetList>;

export default defineComponent({
  name: 'SearchcraftFacetList',
  props: {
    fieldName: {
      type: String as () => Components.SearchcraftFacetList['fieldName'],
      required: true,
    },
  },
  emits: ['facetSelectionUpdated'],
  setup(props: SearchcraftFacetListProps, { emit }) {
    const handleFacetSelectionUpdated = (event: CustomEvent) => {
      emit('facetSelectionUpdated', event);
    };

    return () => (
      <Component
        {...(props as Components.SearchcraftFacetList)}
        onFacetSelectionUpdated={handleFacetSelectionUpdated}
      />
    );
  },
});

// packages/react-sdk/src/components/SearchcraftFacetList.tsx
import type { FC } from 'react';

import { SearchcraftFacetList as Component } from '../stencil-web-components/components';
import type { Components } from '@searchcraft/javascript-sdk';

interface SearchcraftFacetListProps extends Components.SearchcraftFacetList {}

const SearchcraftFacetList: FC<SearchcraftFacetListProps> = (props) => (
  <Component {...props} />
);

export { SearchcraftFacetList };
export type { SearchcraftFacetListProps };
