// packages/vue-sdk/src/components/SearchcraftTheme.vue
<script lang="ts">
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftTheme as Component } from '../stencil-web-components';

export type SearchcraftThemeProps = Components.SearchcraftTheme;

export default defineComponent({
  name: 'SearchcraftTheme',
  props: {},
  components: {
    Component,
  },
});
</script>

<template>
  <Component v-bind="$props" />
</template>

// packages/react-sdk/src/components/SearchcraftTheme.tsx
import type { FC } from 'react';

import { SearchcraftTheme as Component } from '../stencil-web-components/components';
import type { Components } from '@searchcraft/javascript-sdk';

interface SearchcraftThemeProps extends Components.SearchcraftTheme {}

const SearchcraftTheme: FC<SearchcraftThemeProps> = (props) => (
  <Component {...props} />
);

export { SearchcraftTheme };
export type { SearchcraftThemeProps };
