// packages/vue-sdk/src/components/SearchcraftInputForm.tsx
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftInputForm as Component } from '../stencil-web-components';

export type SearchcraftInputFormProps = Partial<Components.SearchcraftInputForm>;

export default defineComponent({
  name: 'SearchcraftInputForm',
  props: {
    config: {
      type: Object as () => Record<string, unknown>,
      required: false,
    },
    autoSearch: {
      type: Boolean,
      default: false,
    },
    buttonPlacement: {
      type: String as () => 'left' | 'right',
      default: 'right',
    },
    buttonLabel: {
      type: String,
      default: 'Search',
    },
    inputLabel: {
      type: String,
      default: '',
    },
    customStyles: {
      type: Object as () => Record<string, string>,
      default: () => ({}),
    },
    placeholderValue: {
      type: String,
      default: 'Enter a search term...',
    },
    searchTerm: {
      type: String,
      default: '',
    },
    debounceDelay: {
      type: Number,
      default: 300,
    },
  },
  emits: [
    'inputCleared',
    'noResultsReceived',
    'querySubmit',
    'inputFocus',
    'inputBlur',
  ],
  setup(props: SearchcraftInputFormProps, { emit }) {
    const emitEvent = (
      eventName: 'inputCleared' | 'noResultsReceived' | 'querySubmit' | 'inputFocus' | 'inputBlur'
    ) => (event: CustomEvent) => {
      emit(eventName, event);
    };

    return () => (
      <Component
        {...(props as Components.SearchcraftInputForm)}
        onInputCleared={emitEvent('inputCleared')}
        onNoResultsReceived={emitEvent('noResultsReceived')}
        onQuerySubmit={emitEvent('querySubmit')}
        onInputFocus={emitEvent('inputFocus')}
        onInputBlur={emitEvent('inputBlur')}
      />
    );
  }
});

// packages/react-sdk/src/components/SearchcraftInputForm.tsx
import type { FC } from 'react';

import { SearchcraftInputForm as Component } from '../stencil-web-components/components';
import type { Components } from '@searchcraft/javascript-sdk';

/**
 * The props for the SearchcraftInputForm.
 */
interface SearchcraftInputFormProps extends Components.SearchcraftInputForm {}

/**
 * A component that provides a user-friendly interface for querying an indexed dataset,
 * enabling users to easily search large collections of data. It abstracts the complexities
 * of index-based searching, making it accessible to users of all technical levels.
 *
 * @example
 * ```tsx
 * import React from 'react';
 * import { SearchcraftInputForm } from '@searchcraft/react-sdk';
 * import searchcraftConfig from './searchcraftConfig';
 *
 * const MySearchComponent = () => {
 *   const handleQuerySubmit = (event: CustomEvent<string>) => {
 *     console.log("Query submitted", event.detail);
 *   };
 *
 *   return (
 *     <SearchcraftInputForm
 *       config={searchcraftConfig}
 *       autoSearch={true}
 *       buttonPlacement="right"
 *       buttonLabel="Search"
 *       inputLabel="Search Database"
 *       customStyles={{ border: "1px solid gray", padding: "5px" }}
 *       placeholderValue="Search here..."
 *       searchTerm=""
 *       onQuerySubmit={handleQuerySubmit}
 *       onInputCleared={() => console.log("Input cleared")}
 *       onNoResultsReceived={() => console.log("No results found")}
 *       onInputFocus={() => console.log("Input focused")}
 *       onInputBlur={() => console.log("Input blurred")}
 *       onInputInit={() => console.log("Input initialized")}
 *     />
 *   );
 * };
 *
 * export default MySearchComponent;
 * ```
 */
const SearchcraftInputForm: FC<SearchcraftInputFormProps> = (props) => (
  <Component {...props} />
);

export { SearchcraftInputForm };
export type { SearchcraftInputFormProps };
