// packages/vue-sdk/src/components/SearchcraftTheme.tsx
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftTheme as Component } from '../stencil-web-components';

export type SearchcraftThemeProps = Partial<Components.SearchcraftTheme>;

export default defineComponent({
  name: 'SearchcraftTheme',
  props: {},
  setup(props: SearchcraftThemeProps) {
    return () => <Component {...(props as Components.SearchcraftTheme)} />;
  },
});

// packages/react-sdk/src/components/SearchcraftTheme.tsx
import type { FC } from 'react';

import { SearchcraftTheme as Component } from '../stencil-web-components/components';
import type { Components } from '@searchcraft/javascript-sdk';

interface SearchcraftThemeProps extends Components.SearchcraftTheme {}

const SearchcraftTheme: FC<SearchcraftThemeProps> = (props) => (
  <Component {...props} />
);

export { SearchcraftTheme };
export type { SearchcraftThemeProps };
