// packages/vue-sdk/src/components/SearchcraftResultsInfo.tsx
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftResultsInfo as Component } from '../stencil-web-components';

export type SearchcraftResultsInfoProps = Partial<Components.SearchcraftResultsInfo>;

export default defineComponent({
  name: 'SearchcraftResultsInfo',
  props: {},
  setup(props: SearchcraftResultsInfoProps) {
    return () => <Component {...(props as Components.SearchcraftResultsInfo)} />;
  },
});

// packages/react-sdk/src/components/SearchcraftResultsInfo.tsx
import type { FC } from 'react';

import { SearchcraftResultsInfo as Component } from '../stencil-web-components/components';
import type { Components } from '@searchcraft/javascript-sdk';

interface SearchcraftResultsInfoProps
  extends Components.SearchcraftResultsInfo {}

const SearchcraftResultsInfo: FC<SearchcraftResultsInfoProps> = (props) => (
  <Component {...props} />
);

export { SearchcraftResultsInfo };
export type { SearchcraftResultsInfoProps };
