// packages/react-sdk/src/client/SearchcraftPopoverForm.tsx
import type { FC } from 'react';

import type { Components } from '@searchcraft/javascript-sdk';
import { SearchcraftPopoverForm as Component } from '../stencil-output/components';

/**
 * The props for the SearchcraftPopoverForm component.
 */
interface SearchcraftPopoverFormProps
  extends Components.SearchcraftPopoverForm {}

/**
 * A component that displays search results in a popover container that dynamically appears
 * when the user interacts with a search input field, or when a popover button is clicked.
 *
 * @example
 * ```tsx
 * import React from 'react';
 * import { SearchcraftPopoverForm } from '@searchcraft/react-sdk';
 * import searchcraftConfig from './searchcraftConfig';
 * import popoverResultMappings from './popoverResultMappings';
 *
 * const MyPopoverSearch = () => {
 *   return (
 *     <SearchcraftPopoverForm
 *       config={searchcraftConfig}
 *       type="fullscreen"
 *       popoverResultMappings={popoverResultMappings}
 *       hotkey="k"
 *       hotkeyModifier="meta"
 *     />
 *   );
 * };
 *
 * export default MyPopoverSearch;
 * ```
 */
const SearchcraftPopoverForm: FC<SearchcraftPopoverFormProps> = (props) => (
  <Component {...props} sdkVariant='react' />
);

export { SearchcraftPopoverForm };
export type { SearchcraftPopoverFormProps };

// packages/vue-sdk/src/components/SearchcraftPopoverForm.tsx
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent, h } from 'vue';
import { SearchcraftPopoverForm as Component } from '../stencil-web-components';

/**
 * The Props for the SearchcraftPopoverForm.
 */
export interface SearchcraftPopoverFormProps
  extends Components.SearchcraftPopoverForm {}

/**
 * A component that displays search results in a popover container that dynamically appears
 * when the user interacts with a search input field, or when a Popover Button has been clicked.
 *
 * @example
 * ```vue
 * <script setup>
 * import SearchcraftPopoverForm from '@searchcraft/vue-sdk';
 * import searchcraftConfig from './searchcraftConfig';
 * import popoverResultMappings from './popoverResultMappings';
 * </script>
 *
 * <template>
 *   <SearchcraftPopoverForm
 *     :config="searchcraftConfig"
 *     type="fullscreen"
 *     :popoverResultMappings="popoverResultMappings"
 *     hotkey="k"
 *     hotkeyModifier="meta"
 *   />
 * </template>
 * ```
 */
const SearchcraftPopoverForm = defineComponent({
  name: 'SearchcraftPopoverForm',
  inheritAttrs: false,
  setup(_, { attrs, slots }) {
    return () => h(Component, { sdkVariant: 'vue', ...attrs }, slots);
  },
});

export { SearchcraftPopoverForm };
