// packages/react-sdk/src/server/SearchcraftPopoverForm.tsx
import type { Components } from '@searchcraft/javascript-sdk';
import { getSearchcraftHtml } from './utils/getSearchcraftHtml';

/**
 * The props for the SearchcraftPopoverForm component.
 */
interface SearchcraftPopoverFormProps
  extends Components.SearchcraftPopoverForm {}

/**
 * A react server component that displays search results in a popover container that dynamically appears
 * when the user interacts with a search input field, or when a popover button is clicked.
 */
export async function SearchcraftPopoverForm(
  props: SearchcraftPopoverFormProps,
) {
  const { tag, html } = await getSearchcraftHtml(
    'searchcraft-popover-form',
    props,
  );

  return (
    <div
      data-sc-component
      data-sc-tag-name='searchraft-popover-form'
      data-sc-tag={tag}
      // biome-ignore lint/security/noDangerouslySetInnerHtml: <explanation>
      dangerouslySetInnerHTML={{ __html: html as TrustedHTML }}
    />
  );
}

// packages/vue-sdk/src/components/SearchcraftPopoverForm.tsx
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent, h } from 'vue';
import { SearchcraftPopoverForm as Component } from '../stencil-web-components';

/**
 * The Props for the SearchcraftPopoverForm.
 */
export interface SearchcraftPopoverFormProps
  extends Components.SearchcraftPopoverForm {}

/**
 * A component that displays search results in a popover container that dynamically appears
 * when the user interacts with a search input field, or when a Popover Button has been clicked.
 *
 * @example
 * ```vue
 * <script setup>
 * import SearchcraftPopoverForm from '@searchcraft/vue-sdk';
 * import searchcraftConfig from './searchcraftConfig';
 * import popoverResultMappings from './popoverResultMappings';
 * </script>
 *
 * <template>
 *   <SearchcraftPopoverForm
 *     :config="searchcraftConfig"
 *     type="fullscreen"
 *     :popoverResultMappings="popoverResultMappings"
 *     hotkey="k"
 *     hotkeyModifier="meta"
 *   />
 * </template>
 * ```
 */
const SearchcraftPopoverForm = defineComponent({
  name: 'SearchcraftPopoverForm',
  inheritAttrs: false,
  setup(_, { attrs, slots }) {
    return () => h(Component, { sdkVariant: 'vue', ...attrs }, slots);
  },
});

export { SearchcraftPopoverForm };
