// packages/react-sdk/src/components/SearchcraftBaseSearchResult/index.tsx
import type { FC } from 'react';

import { SearchcraftBaseSearchResult } from '../../stencil-web-components/components';

export type BaseSearchResultProps = {
  titleContent: string | undefined;
  subtitleContent: string | undefined;
  bodyContent: string | undefined;
  footerContent: string | undefined;
  buttonLabel: string | undefined;
  buttonHref: string | undefined;
  buttonTarget: '_blank' | '_self' | '_top' | '_parent';
  buttonRel: 'noreferrer' | 'noopener' | 'nofollow' | undefined;
  containerHref: string | undefined;
  containerTarget: '_blank' | '_self' | '_top' | '_parent';
  containerRel: 'noreferrer' | 'noopener' | 'nofollow' | undefined;
  customStyles: string | undefined;
  imageAlt: string | undefined;
  imageSrc: string | undefined;
  imagePlacement?: 'left' | 'right';
  documentPosition?: number;
};

const BaseSearchResults: FC<BaseSearchResultProps> = ({
  titleContent = '',
  subtitleContent = '',
  bodyContent = '',
  buttonLabel = '',
  buttonTarget = '_blank',
  buttonHref = '',
  buttonRel = undefined,
  containerHref = undefined,
  containerTarget = '_blank',
  containerRel = undefined,
  customStyles = undefined,
  imageAlt = '',
  imageSrc = '',
  footerContent = '',
  imagePlacement = 'right',
  documentPosition = 1,
}) => (
  <SearchcraftBaseSearchResult
    bodyContent={bodyContent}
    buttonHref={buttonHref}
    buttonLabel={buttonLabel}
    buttonRel={buttonRel}
    buttonTarget={buttonTarget}
    containerHref={containerHref}
    containerRel={containerRel}
    containerTarget={containerTarget}
    customStyles={customStyles}
    documentPosition={documentPosition}
    footerContent={footerContent}
    imageAlt={imageAlt}
    imagePlacement={imagePlacement}
    imageSrc={imageSrc}
    subtitleContent={subtitleContent}
    titleContent={titleContent}
  />
);

export default BaseSearchResults;

// packages/vue-sdk/src/components/SearchcraftBaseSearchResult.vue
<script lang="ts">
import type { Components } from '@searchcraft/javascript-sdk';
import { type PropType, defineComponent } from 'vue';
import { SearchcraftBaseSearchResult as Component } from '../stencil-web-components';

export type SearchcraftBaseSearchResultProps =
  Components.SearchcraftBaseSearchResult;

export default defineComponent({
  name: 'SearchcraftBaseSearchResult',
  props: {
    titleContent: {
      type: String as PropType<string>,
      required: false,
    },
    subtitleContent: {
      type: String as PropType<string>,
      required: false,
    },
    bodyContent: {
      type: String as PropType<string>,
      required: false,
    },
    footerContent: {
      type: String as PropType<string>,
      required: false,
    },
    buttonLabel: {
      type: String as PropType<string>,
      required: false,
    },
    buttonHref: {
      type: String as PropType<string>,
      required: false,
    },
    buttonTarget: {
      type: String as PropType<string>,
      required: false,
    },
    buttonRel: {
      type: String as PropType<string>,
      required: false,
    },
    containerHref: {
      type: String as PropType<string>,
      required: false,
    },
    containerTarget: {
      type: String as PropType<string>,
      required: false,
    },
    containerRel: {
      type: String as PropType<string>,
      required: false,
    },
    imageSrc: {
      type: String as PropType<string>,
      required: false,
    },
    imageAlt: {
      type: String as PropType<string>,
      required: false,
    },
    imagePlacement: {
      type: String as PropType<string>,
      required: false,
    },
    customStyles: {
      type: Object as PropType<Record<string, string>>,
      required: false,
    },
    documentPosition: {
      type: Number as PropType<number>,
      required: false,
    },
  },
  components: {
    Component,
  },
});
</script>

<template>
  <Component v-bind="$props" />
</template>
