// packages/vue-sdk/src/components/SearchcraftInputForm.tsx
import type { Components } from '@searchcraft/javascript-sdk';
import { SearchcraftInputForm as Component } from '../stencil-web-components';

/**
 * The Props for the SearchcraftInputForm component.
 */
export interface SearchcraftInputFormProps
  extends Components.SearchcraftInputForm {}

/**
 * A component that provides a user-friendly interface for querying an indexed dataset,
 * enabling users to easily search large collections of data. It abstracts the complexities
 * of index-based searching, making it accessible to users of all technical levels.
 *
 * @example
 * ```vue
 * <script setup>
 * import SearchcraftInputForm from '@searchcraft/vue-sdk';
 * import searchcraftConfig from './searchcraftConfig';
 *
 * const handleQuerySubmit = (event) => {
 *   console.log("Query submitted", event.detail);
 * };
 * </script>
 *
 * <template>
 *   <SearchcraftInputForm
 *     :config="searchcraftConfig"
 *     :autoSearch="true"
 *     buttonPlacement="right"
 *     buttonLabel="Search"
 *     inputLabel="Search Database"
 *     :customStyles="{ border: '1px solid gray', padding: '5px' }"
 *     placeholderValue="Search here..."
 *     searchTerm=""
 *     @querySubmit="handleQuerySubmit"
 *     @inputCleared="() => console.log('Input cleared')"
 *     @noResultsReceived="() => console.log('No results found')"
 *     @inputFocus="() => console.log('Input focused')"
 *     @inputBlur="() => console.log('Input blurred')"
 *     @inputInit="() => console.log('Input initialized')"
 *   />
 * </template>
 * ```
 */
const SearchcraftInputForm = Component;

export { SearchcraftInputForm };

// packages/vue-sdk/src/components/SearchcraftInputForm.vue
<script lang="ts">
import type { Components } from '@searchcraft/javascript-sdk';
import { type PropType, defineComponent } from 'vue';
import { SearchcraftInputForm as Component } from '../stencil-web-components';

export type SearchcraftInputFormProps = Components.SearchcraftInputForm;

export default defineComponent({
  name: 'SearchcraftInputForm',
  props: {
    config: {
      type: Object as PropType<Record<string, unknown>>,
      required: false,
    },
    autoSearch: {
      type: Boolean as PropType<boolean>,
      default: false,
    },
    buttonPlacement: {
      type: String as PropType<'left' | 'right'>,
      default: 'right',
    },
    buttonLabel: {
      type: String as PropType<string>,
      default: 'Search',
    },
    inputLabel: {
      type: String as PropType<string>,
      default: '',
    },
    customStyles: {
      type: Object as PropType<Record<string, string>>,
      default: () => ({}),
    },
    placeholderValue: {
      type: String as PropType<string>,
      default: 'Enter a search term...',
    },
    searchTerm: {
      type: String as PropType<string>,
      default: '',
    },
    debounceDelay: {
      type: Number as PropType<number>,
      default: 300,
    },
  },
  emits: [
    'inputCleared',
    'noResultsReceived',
    'querySubmit',
    'inputFocus',
    'inputBlur',
  ],
  components: {
    Component,
  },
});
</script>

<template>
  <!-- Pass all props dynamically -->
  <Component
    v-bind="$props"
    @inputCleared="$emit('inputCleared', $event)"
    @noResultsReceived="$emit('noResultsReceived', $event)"
    @querySubmit="$emit('querySubmit', $event)"
    @inputFocus="$emit('inputFocus', $event)"
    @inputBlur="$emit('inputBlur', $event)"
  />
</template>
