// packages/react-sdk/src/components/SearchcraftErrorMessage.tsx
import type { FC } from 'react';

import { SearchcraftErrorMessage as Component } from '../stencil-web-components/components';
import type { Components } from '@searchcraft/javascript-sdk';

interface SearchcraftErrorMessageProps
  extends Components.SearchcraftErrorMessage {}

const SearchcraftErrorMessage: FC<SearchcraftErrorMessageProps> = (props) => (
  <Component {...props} />
);

export { SearchcraftErrorMessage };
export type { SearchcraftErrorMessageProps };

// packages/vue-sdk/src/components/SearchcraftErrorMessage.vue
<script lang="ts">
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftErrorMessage as Component } from '../stencil-web-components';

export type SearchcraftErrorMessageProps = Components.SearchcraftErrorMessage;

export default defineComponent({
  name: 'SearchcraftErrorMessage',
  props: {
    errorMessage: String,
  },
  components: {
    Component,
  },
});
</script>

<template>
  <Component v-bind="$props" />
</template>
