// packages/react-sdk/src/components/SearchcraftResultsInfo.tsx
import type { FC } from 'react';

import { SearchcraftResultsInfo as Component } from '../stencil-web-components/components';
import type { Components } from '@searchcraft/javascript-sdk';

interface SearchcraftResultsInfoProps
  extends Components.SearchcraftResultsInfo {}

const SearchcraftResultsInfo: FC<SearchcraftResultsInfoProps> = (props) => (
  <Component {...props} />
);

export { SearchcraftResultsInfo };
export type { SearchcraftResultsInfoProps };

// packages/vue-sdk/src/components/SearchcraftResultsInfo.vue
<script lang="ts">
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftResultsInfo as Component } from '../stencil-web-components';

export type SearchcraftResultsInfoProps = Components.SearchcraftResultsInfo;

export default defineComponent({
  name: 'SearchcraftResultsInfo',
  props: {},
  components: {
    Component,
  },
});
</script>

<template>
  <Component v-bind="$props" />
</template>
