// packages/react-sdk/src/components/SearchcraftPopoverButton.tsx
import type { FC } from 'react';

import type { Components } from '@searchcraft/javascript-sdk';
import { SearchcraftPopoverButton as Component } from '../stencil-web-components/components';

interface SearchcraftPopoverButtonProps extends Components.SearchcraftPopoverButton { }

const SearchcraftPopoverButton: FC<SearchcraftPopoverButtonProps> = (props) => (
  <Component {...props} />
);

export { SearchcraftPopoverButton };
export type { SearchcraftPopoverButtonProps };

// packages/vue-sdk/src/components/SearchcraftPopoverButton.vue
<script lang="ts">
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftPopoverButton as Component } from '../stencil-web-components';

export type SearchcraftPopoverButtonProps = Components.SearchcraftPopoverButton;

export default defineComponent({
  name: 'SearchcraftPopoverButton',
  props: {},
  components: {
    Component,
  },
});
</script>

<template>
  <Component v-bind="$props" />
</template>
