// packages/react-sdk/src/components/SearchcraftErrorMessage/index.tsx
import type { FC } from 'react';

import { SearchcraftErrorMessage } from '../../stencil-web-components/components';

export type ErrorMessageProps = {
  errorMessage?: string;
};

const ErrorMessage: FC<ErrorMessageProps> = ({
  errorMessage = 'Enter Search',
}) => <SearchcraftErrorMessage errorMessage={errorMessage} />;

export default ErrorMessage;

// packages/vue-sdk/src/components/SearchcraftErrorMessage.vue
<script lang="ts">
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftErrorMessage as Component } from '../stencil-web-components';

export type SearchcraftErrorMessageProps = Components.SearchcraftErrorMessage;

export default defineComponent({
  name: 'SearchcraftErrorMessage',
  props: {
    errorMessage: String,
  },
  components: {
    Component,
  },
});
</script>

<template>
  <Component v-bind="$props" />
</template>
