// packages/react-sdk/src/components/SearchcraftBaseSearchResults/index.tsx
import type { FC } from 'react';

import { SearchcraftBaseSearchResults } from '../../stencil-web-components/components';
import type { SearchResultMappings } from '@searchcraft/javascript-sdk/dist/types/components.js';

export type BaseSearchResultsProps = {
  adInterval: number;
  customStylesForResults:
    | string
    | Record<string, Record<string, string>>
    | undefined;
  searchResultMappings: SearchResultMappings | undefined;
  placeAdAtEnd: boolean;
  placeAdAtStart: boolean;
  resultImagePlacement: 'left' | 'right';
  buttonLabel: string | undefined;
  buttonTarget: '_blank' | '_self' | '_top' | '_parent';
  buttonRel: 'noreferrer' | 'noopener' | 'nofollow' | undefined;
  containerTarget: '_blank' | '_self' | '_top' | '_parent';
  containerRel: 'noreferrer' | 'noopener' | 'nofollow' | undefined;
};

const BaseSearchResults: FC<BaseSearchResultsProps> = ({
  adInterval = 4,
  customStylesForResults = '',
  searchResultMappings,
  placeAdAtEnd = false,
  placeAdAtStart = true,
  resultImagePlacement = 'right',
  buttonLabel = '',
  buttonRel = 'noreferrer',
  buttonTarget = '_blank',
  containerRel = 'noreferrer',
  containerTarget = '_blank',
}) => (
  <SearchcraftBaseSearchResults
    adInterval={adInterval}
    buttonLabel={buttonLabel}
    buttonRel={buttonRel}
    buttonTarget={buttonTarget}
    containerRel={containerRel}
    containerTarget={containerTarget}
    customStylesForResults={customStylesForResults}
    searchResultMappings={searchResultMappings}
    placeAdAtEnd={placeAdAtEnd}
    placeAdAtStart={placeAdAtStart}
    resultImagePlacement={resultImagePlacement}
  />
);

export default BaseSearchResults;

// packages/vue-sdk/src/components/SearchcraftBaseSearchResults.tsx
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftBaseSearchResults as Component } from '../stencil-web-components';

export type SearchcraftBaseSearchResultsProps = Partial<Components.SearchcraftBaseSearchResults>;

export default defineComponent({
  name: 'SearchcraftBaseSearchResults',
  props: {
    adInterval: Number,
    customStylesForResults: Object as () => Record<string, string>,
    searchResultMappings: Object as () => Record<string, string>,
    placeAdAtEnd: Boolean,
    placeAdAtStart: Boolean,
    resultImagePlacement: String,
    buttonLabel: String,
    buttonTarget: String,
    buttonRel: String,
    containerTarget: String,
    containerRel: String,
    noResults: String,
  },
  setup(props: SearchcraftBaseSearchResultsProps) {
    return () => <Component {...(props as Components.SearchcraftBaseSearchResults)} />;
  },
});
