// packages/react-sdk/src/components/SearchcraftBaseSearchResults.tsx
import type { FC } from 'react';

import { SearchcraftBaseSearchResults as Component } from '../stencil-web-components/components';
import type { Components } from '@searchcraft/javascript-sdk';

interface SearchcraftBaseSearchResultsProps
  extends Components.SearchcraftBaseSearchResults {}

const SearchcraftBaseSearchResults: FC<SearchcraftBaseSearchResultsProps> = (
  props,
) => <Component {...props} />;

export { SearchcraftBaseSearchResults };
export type { SearchcraftBaseSearchResultsProps };

// packages/vue-sdk/src/components/SearchcraftBaseSearchResults.vue
<script lang="ts">
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftBaseSearchResults as Component } from '../stencil-web-components';

export type SearchcraftBaseSearchResultsProps =
  Components.SearchcraftBaseSearchResults;

export default defineComponent({
  name: 'SearchcraftBaseSearchResults',
  props: {
    adInterval: Number,
    customStylesForResults: Object,
    searchResultMappings: Object,
    placeAdAtEnd: Boolean,
    placeAdAtStart: Boolean,
    resultImagePlacement: String,
    buttonLabel: String,
    buttonTarget: String,
    buttonRel: String,
    containerTarget: String,
    containerRel: String,
    noResults: String,
  },
  components: {
    Component,
  },
});
</script>

<template>
  <Component v-bind="$props" />
</template>
