// packages/vue-sdk/src/components/SearchcraftPopoverButton.tsx
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftPopoverButton as Component } from '../stencil-web-components';

export type SearchcraftPopoverButtonProps = Partial<Components.SearchcraftPopoverButton>;

export default defineComponent({
  name: 'SearchcraftPopoverButton',
  props: {},
  setup(props: SearchcraftPopoverButtonProps) {
    return () => <Component {...(props as Components.SearchcraftPopoverButton)} />;
  },
});

// packages/react-sdk/src/client/SearchcraftPopoverButton.tsx
import type { FC } from 'react';

import type { Components } from '@searchcraft/javascript-sdk';
import { SearchcraftPopoverButton as Component } from '../stencil-output/components';

/**
 * The props for the SearchcraftPopoverButton.
 */
interface SearchcraftPopoverButtonProps
  extends Components.SearchcraftPopoverButton {}

/**
 * A button component that, when clicked, toggles the visibility of a popover.
 *
 * @example
 * ```tsx
 * import React from 'react';
 * import { SearchcraftPopoverButton } from '@searchcraft/react-sdk';
 *
 * const MyPopoverTrigger = () => {
 *   return (
 *     <SearchcraftPopoverButton>
 *       Open Popover
 *     </SearchcraftPopoverButton>
 *   );
 * };
 *
 * export default MyPopoverTrigger;
 * ```
 */
const SearchcraftPopoverButton: FC<SearchcraftPopoverButtonProps> = (props) => (
  <Component {...props} />
);

export { SearchcraftPopoverButton };
export type { SearchcraftPopoverButtonProps };
