// packages/vue-sdk/src/components/SearchcraftFacetList.vue
<script lang="ts">
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftFacetList as Component } from '../stencil-web-components';

export type SearchcraftFacetListProps = Components.SearchcraftFacetList;

export default defineComponent({
  name: 'SearchcraftFacetList',
  props: {
    fieldName: {
      type: String as () => Components.SearchcraftFacetList['fieldName'],
      required: true,
    },
  },
  emits: ['facetSelectionUpdated'],
  components: {
    Component,
  },
});
</script>

<template>
  <Component
    v-bind="$props"
    @facetSelectionUpdated="$emit('facetSelectionUpdated', $event)"
  />
</template>

// packages/react-sdk/src/components/SearchcraftFacetList/index.tsx
import type { FC } from 'react';

import { SearchcraftFacetList } from '../../stencil-web-components/components';

export type FacetListProps = {
  fieldName: string;
};

const FacetList: FC<FacetListProps> = ({ fieldName = '' }) => (
  <SearchcraftFacetList fieldName={fieldName} />
);

export default FacetList;
