// packages/react-sdk/src/components/SearchcraftBaseSearchResult/index.tsx
import type { FC } from 'react';

import { SearchcraftBaseSearchResult } from '../../stencil-web-components/components';

export type BaseSearchResultProps = {
  titleContent: string | undefined;
  subtitleContent: string | undefined;
  bodyContent: string | undefined;
  footerContent: string | undefined;
  buttonLabel: string | undefined;
  buttonHref: string | undefined;
  buttonTarget: '_blank' | '_self' | '_top' | '_parent';
  buttonRel: 'noreferrer' | 'noopener' | 'nofollow' | undefined;
  containerHref: string | undefined;
  containerTarget: '_blank' | '_self' | '_top' | '_parent';
  containerRel: 'noreferrer' | 'noopener' | 'nofollow' | undefined;
  customStyles: string | undefined;
  imageAlt: string | undefined;
  imageSrc: string | undefined;
  imagePlacement?: 'left' | 'right';
  documentPosition?: number;
};

const BaseSearchResults: FC<BaseSearchResultProps> = ({
  titleContent = '',
  subtitleContent = '',
  bodyContent = '',
  buttonLabel = '',
  buttonTarget = '_blank',
  buttonHref = '',
  buttonRel = undefined,
  containerHref = undefined,
  containerTarget = '_blank',
  containerRel = undefined,
  customStyles = undefined,
  imageAlt = '',
  imageSrc = '',
  footerContent = '',
  imagePlacement = 'right',
  documentPosition = 1,
}) => (
  <SearchcraftBaseSearchResult
    bodyContent={bodyContent}
    buttonHref={buttonHref}
    buttonLabel={buttonLabel}
    buttonRel={buttonRel}
    buttonTarget={buttonTarget}
    containerHref={containerHref}
    containerRel={containerRel}
    containerTarget={containerTarget}
    customStyles={customStyles}
    documentPosition={documentPosition}
    footerContent={footerContent}
    imageAlt={imageAlt}
    imagePlacement={imagePlacement}
    imageSrc={imageSrc}
    subtitleContent={subtitleContent}
    titleContent={titleContent}
  />
);

export default BaseSearchResults;

// packages/javascript-sdk/src/components/searchcraft-base-search-result/searchcraft-base-search-result.tsx
import { useSearchcraftStore } from '@provider/store';
import { Component, Fragment, h, Prop } from '@stencil/core';

@Component({
  tag: 'searchcraft-base-search-result',
  styleUrl: 'searchcraft-base-search-result.module.scss',
  shadow: false,
})
export class SearchcraftBaseSearchResult {
  @Prop() titleContent: string | undefined;
  @Prop() subtitleContent: string | undefined;
  @Prop() bodyContent: string | undefined;
  @Prop() footerContent: string | undefined;
  @Prop() buttonLabel: string | undefined;
  @Prop() buttonHref: string | undefined;
  @Prop() buttonTarget: '_blank' | '_self' | '_top' | '_parent' = '_blank';
  @Prop() buttonRel: 'noreferrer' | 'noopener' | 'nofollow' | undefined;
  @Prop() containerHref: string | undefined;
  @Prop() containerTarget: '_blank' | '_self' | '_top' | '_parent' = '_blank';
  @Prop() containerRel: 'noreferrer' | 'noopener' | 'nofollow' | undefined;
  @Prop() imageSrc: string | undefined;
  @Prop() imageAlt: string | undefined;
  @Prop() imagePlacement: 'left' | 'right';
  @Prop() customStyles: string | undefined;
  @Prop() documentPosition = 0;

  private searchcraftStore = useSearchcraftStore.getState();

  private recordMeasureEvent = () => {
    const searchcraft = this.searchcraftStore.getSearchcraftInstance();

    if (searchcraft) {
      const document_position = this.documentPosition;
      const search_term = this.searchcraftStore.query;
      const number_of_documents =
        this.searchcraftStore.searchResults?.data?.hits?.length || 0;

      searchcraft.sendMeasureEvent('document_clicked', {
        document_position,
        number_of_documents,
        search_term,
      });
    }
  };

  private parseStyles = (): Record<string, { [key: string]: string }> => {
    if (this.customStyles) {
      try {
        return JSON.parse(this.customStyles);
      } catch (error) {
        console.error('Error parsing custom styles:', error);
        return {};
      }
    }
  };

  render() {
    const styles = this.parseStyles();
    const imageContainer = this.imageSrc && (
      <img
        alt={this.imageAlt}
        class='searchcraft-search-result-image'
        src={this.imageSrc}
        style={styles.image || {}}
      />
    );

    const contentContainer = (
      <Fragment>
        {this.imageSrc && this.imagePlacement === 'left' && imageContainer}
        <div class='searchcraft-base-search-result-content-container'>
          {this.titleContent && (
            <h2
              class='searchcraft-base-search-result-title'
              style={styles.title || {}}
            >
              {this.titleContent}
            </h2>
          )}
          {this.subtitleContent && (
            <h3
              class='searchcraft-base-search-result-subtitle'
              style={styles.subtitle || {}}
            >
              {this.subtitleContent}
            </h3>
          )}
          {this.bodyContent && (
            <p
              class='searchcraft-base-search-result-body-content'
              style={styles.primaryContent || {}}
            >
              {this.bodyContent}
            </p>
          )}

          {this.footerContent && (
            <p
              class='searchcraft-base-search-result-footer-content'
              style={styles.secondaryContent || {}}
            >
              {this.footerContent}
            </p>
          )}
          {this.buttonHref && !this.containerHref && this.buttonLabel && (
            <a
              class='searchcraft-search-result-button'
              href={this.buttonHref}
              style={styles.button || {}}
              target={this.buttonTarget}
              rel={this.buttonRel}
            >
              {this.buttonLabel}
            </a>
          )}
        </div>
        {this.imageSrc && this.imagePlacement === 'right' && imageContainer}
      </Fragment>
    );

    /** Render as an anchor tag if the containerHref prop is present. */
    if (this.containerHref) {
      return (
        <a
          class='searchcraft-search-result-container'
          onClick={this.recordMeasureEvent}
          href={this.containerHref}
          rel={this.containerRel}
          style={styles.container || {}}
          tabindex='0'
          target={this.containerTarget}
        >
          {contentContainer}
        </a>
      );
    }

    /** Render as a div if no href prop. */
    return (
      <div
        class='searchcraft-search-result-container'
        style={styles.container || {}}
      >
        {contentContainer}
      </div>
    );
  }
}
