// packages/vue-sdk/src/components/SearchcraftSlider.vue
<script lang="ts">
import type { Components } from '@searchcraft/javascript-sdk';
import { defineComponent } from 'vue';
import { SearchcraftSlider as Component } from '../stencil-web-components';

export type SearchcraftSliderProps = Components.SearchcraftSlider;

export default defineComponent({
  name: 'SearchcraftSlider',
  props: {
    max: {
      type: Number as () => Components.SearchcraftSlider['max'],
      required: false,
    },
    min: {
      type: Number as () => Components.SearchcraftSlider['min'],
      required: false,
    },
    granularity: {
      type: Number as () => Components.SearchcraftSlider['granularity'],
      required: false,
    },
    dataType: {
      type: String as () => Components.SearchcraftSlider['dataType'],
      required: false,
    },
  },
  emits: ['rangeChanged'],
  components: {
    Component,
  },
});
</script>

<template>
  <Component
    v-bind="$props"
    @rangeChanged="$emit('rangeChanged', $event)"
  />
</template>

// packages/react-sdk/src/components/SearchcraftSlider/index.tsx
import type { FC } from 'react';

import { SearchcraftSlider } from '../../stencil-web-components/components';

export type SliderProps = {
  dataType: 'number' | 'date';
  granularity: number;
  max: number;
  min: number;
};

const Slider: FC<SliderProps> = ({
  dataType = 'number',
  granularity = 0,
  max = 100,
  min = 0,
}) => (
  <SearchcraftSlider
    dataType={dataType}
    granularity={granularity}
    max={max}
    min={min}
  />
);

export default Slider;
